language: cpp
compiler:
  - gcc
script:
  - gcc -O2 ./utils/platypus.c -o ./utils/platypus
  - mkdir report
  - files=`find . -name \*.h -print -o -name \*.cpp -print | sed -e ':a;N;$!ba;s/\n/ /g'`
  - ./utils/platypus -o ./report $files
after_success:
  "for i in report/*; do echo $i; curl --ftp-create-dirs -T ./$i ftp://85.143.2.188/$i; done;"
notifications:
  email: false

